- name: Install eduroam Identity Provider
  hosts: idp
  become: True
  vars_files:
    - group_vars/secrets.yml
  roles:
    - freeradius
    - { role: eapol_test, when: play_eapol == True }
    - { role: newrelic, when: play_newrelic == True }
    
  handlers:
    - name: restart freeradius
      service: name=freeradius state=restarted
