- name: Install Freeradius
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
  with_items:
    - freeradius
    - freeradius-ldap

- name: Copy clients.conf
  template: > 
    src=clients.conf.j2 
    dest=/etc/freeradius/clients.conf
    backup=yes
  notify: restart freeradius

- name: Copy proxy.conf
  template: > 
    src=proxy.conf.j2 
    dest=/etc/freeradius/proxy.conf
    backup=yes
  notify: restart freeradius

- name: Copy eap.conf
  template: > 
    src=eap.conf.j2 
    dest=/etc/freeradius/eap.conf
    backup=yes
  notify: restart freeradius

- name: Copy modules/ldap
  template: > 
    src=modules-ldap.j2 
    dest=/etc/freeradius/modules/ldap
    backup=yes
  notify: restart freeradius

- name: Add test user
  template: > 
    src=users.j2 
    dest=/etc/freeradius/users
    backup=yes
  notify: restart freeradius

- name: Copy sites/default-eduroam
  template: > 
    src=sites_default-eduroam.j2 
    dest=/etc/freeradius/sites-available/default-eduroam
  notify: restart freeradius

- name: Enable sites/default-eduroam
  file: >
    src=/etc/freeradius/sites-available/default-eduroam 
    dest=/etc/freeradius/sites-enabled/default-eduroam
    state=link 
  notify: restart freeradius

- name: Copy sites/inner-tunnel-eduroam
  template: > 
    src=sites_inner-tunnel-eduroam.j2 
    dest=/etc/freeradius/sites-available/inner-tunnel-eduroam
  notify: restart freeradius

- name: Enable sites/inner-tunnel-eduroam
  file: >
    src=/etc/freeradius/sites-available/inner-tunnel-eduroam 
    dest=/etc/freeradius/sites-enabled/inner-tunnel-eduroam
    state=link
  notify: restart freeradius


- name: Copy private key
  copy: > 
    src={{ domain }}.key 
    dest=/etc/ssl/private/{{ domain }}.key
    owner=root
    group=ssl-cert
    mode=0640
    backup=yes
  notify: restart freeradius

- name: Link private key
  file: > 
    src=/etc/ssl/private/{{ domain }}.key 
    dest=/etc/freeradius/certs/{{ domain }}.key
    state=link
  notify: restart freeradius

- name: Copy public key
  copy: > 
    src={{ domain }}.crt 
    dest=/etc/ssl/certs/{{ domain }}.crt
    backup=yes
  notify: restart freeradius

- name: Link public key
  file: > 
    src=/etc/ssl/certs/{{ domain }}.crt 
    dest=/etc/freeradius/certs/{{ domain }}.crt
    state=link
  notify: restart freeradius