- name: Install Make
  apt: pkg={{ item }} update_cache=yes cache_valid_time=36000
  with_items:
    - build-essential
    - libssl-dev
    - libnl-dev

- name: Download wpa_supplicant
  get_url:  url=http://w1.fi/releases/wpa_supplicant-2.5.tar.gz
            dest=/opt/wpa_supplicant-2.5.tar.gz

- name: Extract wpa_supplicant
  unarchive:  src=/opt/wpa_supplicant-2.5.tar.gz
              dest=/opt
              copy=no

- name: Move config
  copy: src=/opt/wpa_supplicant-2.5/wpa_supplicant/defconfig
        dest=/opt/wpa_supplicant-2.5/wpa_supplicant/.config
        remote_src=true

- name: Enable eapol_test
  replace:  dest=/opt/wpa_supplicant-2.5/wpa_supplicant/.config
            regexp='#CONFIG_EAPOL_TEST=y' 
            replace='CONFIG_EAPOL_TEST=y'

- name: Compile the stuff
  make: chdir=/opt/wpa_supplicant-2.5/wpa_supplicant
        target=eapol_test

- name: Move eapol_test bin
  copy: dest=/usr/local/bin/eapol_test
        src=/opt/wpa_supplicant-2.5/wpa_supplicant/eapol_test
        remote_src=true
        mode=755

